#!/data/data/com.termux/files/usr/bin/bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP="$ROOT_DIR/modules/app.sh"
HELP="$ROOT_DIR/modules/help.sh"
bash -n "$APP"
bash -n "$HELP"
grep -Fq 'menu_ambiente_hub()' "$APP"
grep -Fq 'menu_ajuda_sobre_hub()' "$APP"
grep -Fq '1|📁|Gerenciar projetos|Abrir, testar e organizar' "$APP"
grep -Fq '2|🚦|Em execução|$ativos componente(s) ativo(s)' "$APP"
grep -Fq '3|📦|Importar projeto|Pasta, arquivo ou ZIP' "$APP"
grep -Fq '4|🐧|Linux no celular|Distros, PRoot e Termux:X11' "$APP"
grep -Fq '5|🛠️|Ambiente e ferramentas|Termux, pacotes e diagnóstico' "$APP"
grep -Fq '6|🔄|Atualizar Manager|GitHub main ou arquivo local' "$APP"
grep -Fq '7|⚙️|Configurações|Preferências e manutenção' "$APP"
grep -Fq '8|❓|Ajuda e Sobre|Manual, versão e desenvolvedor' "$APP"
grep -Fq 'Projetos: $projetos • Ativos: $ativos' "$APP"
echo "OK: menu principal mantém oito acessos úteis visíveis e agrupa apenas funções secundárias."
